services:
  - type: web
    name: epub-speedread
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 180 --graceful-timeout 180 --workers 1
    autoDeploy: true
